// src/redux/actionTypes.js
export const SET_FORM_DATA = "SET_FORM_DATA";
export const RESET_FORM = "RESET_FORM";

// src/redux/Booking/actionTypes.js
export const FETCH_DC_REQUEST = "FETCH_DC_REQUEST";
export const FETCH_DC_SUCCESS = "FETCH_DC_SUCCESS";
export const FETCH_DC_FAILURE = "FETCH_DC_FAILURE";

export const FETCH_AVAILABLE_SEATS_REQUEST = "FETCH_AVAILABLE_SEATS_REQUEST";
export const FETCH_AVAILABLE_SEATS_SUCCESS = "FETCH_AVAILABLE_SEATS_SUCCESS";
export const FETCH_AVAILABLE_SEATS_FAILURE = "FETCH_AVAILABLE_SEATS_FAILURE";

// src/redux/actionTypes.js
export const BOOK_SEAT_REQUEST = "BOOK_SEAT_REQUEST";
export const BOOK_SEAT_SUCCESS = "BOOK_SEAT_SUCCESS";
export const BOOK_SEAT_FAILURE = "BOOK_SEAT_FAILURE";
